project_id = "hangyeol"

[api]
enabled = true
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 15

[auth]
enable_anonymous_sign_ins = true

[functions.get-profile-summary]
verify_jwt = false