/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/post-concern`; params?: Router.UnknownInputParams; } | { pathname: `/post-concern/my-concerns`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/inbox/[deliveryId]`, params: Router.UnknownInputParams & { deliveryId: string | number; } } | { pathname: `/post-concern/my-concerns/[concernId]`, params: Router.UnknownInputParams & { concernId: string | number; } } | { pathname: `/post-concern/my-concerns/responses/[responseId]`, params: Router.UnknownInputParams & { responseId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/inbox`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/post-concern`; params?: Router.UnknownOutputParams; } | { pathname: `/post-concern/my-concerns`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/inbox/[deliveryId]`, params: Router.UnknownOutputParams & { deliveryId: string; } } | { pathname: `/post-concern/my-concerns/[concernId]`, params: Router.UnknownOutputParams & { concernId: string; } } | { pathname: `/post-concern/my-concerns/responses/[responseId]`, params: Router.UnknownOutputParams & { responseId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/inbox${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/post-concern${`?${string}` | `#${string}` | ''}` | `/post-concern/my-concerns${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/inbox`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/post-concern`; params?: Router.UnknownInputParams; } | { pathname: `/post-concern/my-concerns`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | `/inbox/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/post-concern/my-concerns/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/post-concern/my-concerns/responses/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/inbox/[deliveryId]`, params: Router.UnknownInputParams & { deliveryId: string | number; } } | { pathname: `/post-concern/my-concerns/[concernId]`, params: Router.UnknownInputParams & { concernId: string | number; } } | { pathname: `/post-concern/my-concerns/responses/[responseId]`, params: Router.UnknownInputParams & { responseId: string | number; } };
    }
  }
}
